name: materials
description: Material database

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-120.0.dev <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # GET
  get: ^4.3.8
  get_storage: ^2.0.3
  # FIREBASE
  firebase_core: ^1.6.0
  firebase_database: ^8.0.0

  logger: ^1.1.0
  url_launcher: ^6.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
